# Generated by Django 4.2.3 on 2023-08-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_userpayment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coup_name', models.CharField(max_length=100)),
                ('multi', models.IntegerField(default=1)),
            ],
        ),
    ]
