# Generated by Django 4.2.3 on 2023-08-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catag', models.CharField(blank=True, max_length=50, null=True)),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip', models.CharField(blank=True, max_length=1000, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.userpro')),
            ],
        ),
    ]
