# Generated by Django 4.2.3 on 2023-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_blogs1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs1',
            name='intro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
