# Generated by Django 4.2.3 on 2023-08-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_blogs1_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs1',
            name='descrip',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='blogs1',
            name='intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
