# Generated by Django 4.2.3 on 2023-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_blogs1_descrip_alter_blogs1_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs1',
            name='descrip',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
